# Generated by Django 5.0.3 on 2024-03-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='recipe_description_model',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='recipe_image_model',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='recipe_name_model',
        ),
    ]
